### ISSUE TITLE
Compatibility with Riak 1.4

### ISSUE THREAD

**Issue by pavelsmolka** [php-riak/riak-client#5]
I understand this project aims predominantly to Riak 2.0. However, for people still using Riak 1.4 (like me), there is no easy way to try the library (with the existing cluster, settings), start using it and then safely migrate the cluster. The problem is when you migrate the cluster to 2.0, you cannot use the other C-based php_riak library anymore.

Is this client already backward-compatible, e.g. ready to work with Riak 1.4? If not, do you have a plan to extend it, maybe in a separate branch, to support the older version of Riak as well?

**Comment by KasparBP** [comment]
fwiw php_riak should be 2.0 compatible unless you enable ssl, of cause no new features.

**Comment by FabioBatSilva** [comment]
@pavelsmolka I believe it`s possible to make it work for same basic functionality,
But a have no plans to this for now, once I get the first release out of the door I'll take a look on 1.4 compatibility.

**Comment by FabioBatSilva** [comment]
Confirmed,
Although its not the focus of this client it "works" with riak `1.4` for most kv operations.
