### ISSUE TITLE
Batching requests (send them concurrently)

### ISSUE THREAD

**Issue by mamciek** [php-riak/riak-client#6]
GuzzlePHP allows to send requests concurrently (using curl_multi_exec). How can it be implemented in riak-client? I am willing to work on that.
http://docs.guzzlephp.org/en/latest/clients.html#batching-requests

Can it be implemented by adding metod `batch(array $riakCommands)` to `Riak\Client\RiakClient` (and to all internally called interfaces) ?

**Comment by FabioBatSilva** [comment]
Hi @mamciek 

Not all Riak commands make sense to be done concurrently,
It  would have to be implemented specific of each command.

Fetch value is probably the one that makes more sense to start with, see [java implementation](http://basho.github.io/riak-java-client/2.0.0/com/basho/riak/client/api/commands/kv/MultiFetch.html)

You would have to implement : 
- [MultiFetch Command](https://github.com/php-riak/riak-client/tree/master/src/Riak/Client/Command/Kv)
- [MultiFetch Operation](https://github.com/php-riak/riak-client/tree/master/src/Riak/Client/Core/Operation/Kv)
- [MultiFetch{Request,Response} Message](https://github.com/php-riak/riak-client/tree/master/src/Riak/Client/Core/Message/Kv)
-  [MultiFetch Http Transport](https://github.com/php-riak/riak-client/tree/master/src/Riak/Client/Core/Transport/Http/Kv)

Let me know if you need help.

**Comment by mamciek** [comment]
Thanks.

Fetching KV and Datatypes certainly makes sense to be done concurrently. What about updating/storing values in Riak? It does make sense in my opinion. I think it even makes sense to batch together request of different type, for example fetchKV, fetchDataType, UpdateMap and so on.

**Comment by FabioBatSilva** [comment]
Indeed the most common use would be fetching,

I'd like to keep the batch command base, 
dealing with different response types might be complicated.

We might have something like : 

``` php
/** @var $multiFetch Kv\MultiFetchCommand*/
/** @var $response FetchValueResponse[] */
$result = $client->execute($multiFetch);


/** @var $multiFetchCounter DataTyoe\MultiFetchCounterCommand*/
/** @var $counterResult FetchCounterResponse[] */
$counterResult = $client->execute($multiFetchCounter);
```

In this case all the response objects share the same response type, 
`$response` can either be a `FetchValueResponse` array or a collection/iterator

**Comment by mamciek** [comment]
In the meantime I created simple prototype: https://github.com/php-riak/riak-client/pull/7
It deals only with FetchMap, but you can get the vision. With this approach I would be able to batch multiple type of commands. What do you think ?

**Comment by FabioBatSilva** [comment]
Cool,

We can discuss more on https://github.com/php-riak/riak-client/pull/7 now..
